name : Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        ## Steps 1
        - name: check out code
          uses: actions/checkout@v2
        
        ## Steps 2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        ## Steps 3
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        ## Steps 4
        - name: Run tests
          run: pytest
        
